### ISSUE TITLE
encoding issue?

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#11]
"Γεια"

Results in:

\u can only be followed by a Unicode character sequence
eval@[native code]
file:///replete/core.js:78:59
replete$core$read_eval_print@file:///replete/core.js:89:3

**Comment by venantius** [comment]
I have now hit this issue.

**Comment by mfikes** [comment]
Right, with Planck 1.9:

```
cljs.user=> "Γεια"
\u can only be followed by a Unicode character sequence
	 eval (NO_SOURCE_FILE)
	 cljs$js$eval_str_STAR__$_compile_loop (cljs/js.cljs:1692:16)
	 cljs$js$eval_str_STAR_ (cljs/js.cljs:1714:6)
	 cljs$core$IFn$_invoke$arity$5 (cljs/js.cljs:1817:30)
```

and Planck 1.10 (master):

```
cljs.user=> "Γεια"
"Γεια"
```

Presumably upstream. http://dev.clojure.org/jira/browse/CLJS-1573

**Comment by dotemacs** [comment]
Since the latest Planck is 1.17 and this issue was resolved a while back, but also entering "Γεια" does return "Γεια", can this issue be closed now?

Thanks

**Comment by mfikes** [comment]
Confirmed fixed in Replete.
