### ISSUE TITLE
namespace-qualified keyword breaks

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#12]
::foo

Invalid token: ::foo
cljs$core$ExceptionInfo@file:///cljs/core.js:33152:19
cljs$core$IFn$_invoke$arity$3@file:///cljs/core.js:33214:36
cljs$core$IFn$_invoke$arity$2@file:///cljs/core.js:33210:55
cljs$core$ex_info@file:///cljs/core.js:33196:55
cljs$core$IFn$_invoke$arity$variadic@file:///cljs/tools/reader/reader_types.js:802:29
cljs$tools$reader$reader_types$reader_error@file:///cljs/tools/reader/reader_types.js:798:88
cljs$tools$reader$read_keyword@file:///cljs/tools/reader.js:668:56
file:///cljs/tools/reader.js:1582:17
cljs$tools$reader$reader_types$log_source@file:///cljs/tools/reader/reader_types.js:873:20
cljs$tools$reader$target@file:///cljs/tools/reader.js:1556:54
cljs$core$IFn$_invoke$arity$6@file:///cljs/tools/reader.js:1598:8
cljs$tools$reader$read_STAR_@file:///cljs/tools/reader.js:1541:66
cljs$core$IFn$_invoke$arity$2@file:///cljs/tools/reader.js:1665:41
cljs$tools$reader$read@file:///cljs/tools/reader.js:1643:60
cljs$core$IFn$_invoke$arity$2@file:///cljs/tools/reader.js:1711:35
cljs$tools$reader$read_string@file:///cljs/tools/reader.js:1690:67
cljs$core$IFn$_invoke$arity$1@file:///cljs/tools/reader.js:1700:42
cljs$tools$reader$read_string@file:///cljs/tools/reader.js:1686:67
replete$core$read_eval_print@file:///replete/core.js:40:46

**Comment by kanaka** [comment]
Work in plain REPL:

```
cljs-bootstrap.repl> ::foo
:cljs-bootstrap.repl/foo
```

**Comment by mfikes** [comment]
Updating ClojureScript and properly building with Nolan's `tools.reader` `cljs-boostrap` branch fixed this.
