### ISSUE TITLE
doseq can't recur here

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#13]
`(doseq [x (range 2)] (prn x))`

Can't recur here
cljs$core$ExceptionInfo@file:///cljs/core.js:33152:19
cljs$core$IFn$_invoke$arity$3@file:///cljs/core.js:33214:36
cljs$core$ex_info@file:///cljs/core.js:33200:55
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:699:30
cljs$analyzer$error@file:///cljs/analyzer.js:685:57
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:695:32
cljs$analyzer$error@file:///cljs/analyzer.js:681:57
file:///cljs/analyzer.js:2188:31
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:2076:82
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:2156:38
cljs$analyzer$analyze_let@file:///cljs/analyzer.js:2160:4
file:///cljs/analyzer.js:2164:38
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3776:34
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:1427:38
file:///cljs/analyzer.js:1429:4
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:3537:34
file:///cljs/core.js:16877:92
file:///cljs/core.js:16878:3
file:///cljs/core.js:11035:133
sval@file:///cljs/core.js:11036:3
cljs$core$ISeqable$_seq$arity$1@file:///cljs/core.js:11127:14
cljs$core$seq@file:///cljs/core.js:4731:44
cljs$core$INext$_next$arity$1@file:///cljs/core.js:10603:21
cljs$core$next@file:///cljs/core.js:4840:42
cljs$core$IFn$_invoke$arity$3@file:///cljs/core.js:8379:29
cljs$core$IReduce$_reduce$arity$3@file:///cljs/core.js:11097:58
cljs$core$IFn$_invoke$arity$3@file:///cljs/core.js:8478:46
cljs$core$vec@file:///cljs/core.js:18963:82
cljs$analyzer$parse_invoke@file:///cljs/analyzer.js:3535:34
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3767:39
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:1433:38
file:///cljs/analyzer.js:1435:4
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:2076:82
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///cljs/analyzer.js:2156:38
cljs$analyzer$analyze_let@file:///cljs/analyzer.js:2160:4
file:///cljs/analyzer.js:2167:38
G__11383__6@file:///cljs/core.js:31414:153
G__11383@file:///cljs/core.js:32042:24
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3765:32
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3776:34
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:3776:34
cljs$analyzer$analyze_seq@file:///cljs/analyzer.js:3726:63
file:///cljs/analyzer.js:3981:38
cljs$core$IFn$_invoke$arity$4@file:///cljs/analyzer.js:4011:4
cljs$analyzer$analyze@file:///cljs/analyzer.js:3923:59
cljs$core$IFn$_invoke$arity$3@file:///cljs/analyzer.js:3937:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3919:59
cljs$core$IFn$_invoke$arity$2@file:///cljs/analyzer.js:3933:34
cljs$analyzer$analyze@file:///cljs/analyzer.js:3915:59
file:///replete/core.js:45:38
replete$core$read_eval_print@file:///replete/core.js:47:4

**Comment by kanaka** [comment]
Something messed up with the formatting so I can actually see what your original test is, but this works for me in the plain REPL:

```
cljs-bootstrap.repl> (doseq [x (range 2)] (prn (+ 10 x)))
10
11
nil
```

**Comment by mfikes** [comment]
After updating to latest ClojureScript and `tools.reader`, this one is still broken for Replete.

**Comment by mfikes** [comment]
Now fixed, presumably owing to updating deps.
