### ISSUE TITLE
analyzer warnings

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#21]
If you evaluate an undefined var, say `x`, you will get `nil`. Perhaps the analyzer is emitting warnings that Replete is not showing?

**Comment by kanaka** [comment]
Yeah, same problem in plain bootstrapped REPL. I just pushed a fix:

```
--- a/src/cljs_bootstrap/repl.cljs
+++ b/src/cljs_bootstrap/repl.cljs
@@ -76,7 +76,7 @@
             (try
               (let [form (r/read-string line)
                     _ (when DEBUG (prn "form:" form))
-                    ast (no-warn (ana/analyze env form))
+                    ast (ana/analyze env form)
                     _ (when DEBUG (prn "ast:" ast))
                     js (with-out-str
                          (ensure
```

I had copied the no-warn from an earlier @swannodette example.

**Comment by swannodette** [comment]
ClojureScript will need to split printing from error printing for this problem to be solved.

**Comment by mfikes** [comment]
![analyzer](https://cloud.githubusercontent.com/assets/1723464/8446441/6d82e9ac-1f78-11e5-9a52-02e89543d71c.png)
@swannodette FWIW, @kanaka 's solution works in Replete ^
