### ISSUE TITLE
defrecord doesn't work

### ISSUE THREAD

**Issue by aengelberg** [mfikes/replete#25]
```clojure
> (defprotocol P)
nil
> (reify)
#<[object Object]>
> (reify P)
#<[object Object]>
> (defrecord MyRecord [x])
undefined is not a function
...
```
Maybe defrecord is not yet implemented?

**Comment by aengelberg** [comment]
There's a different error in the cljs repl from the famous 3-step tweet.
```clojure
cljs-bootstrap.repl> (defrecord R [])
Error
    at new cljs$core$ExceptionInfo ([stdin]:33197:11)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 ([stdin]:33238:10)
    at cljs$core$ex_info ([stdin]:33228:32)
    at Function.cljs.analyzer.error.cljs$core$IFn$_invoke$arity$3 ([stdin]:38612:28)
    at cljs$analyzer$error ([stdin]:38602:34)
    at cljs$analyzer$macroexpand_1 ([stdin]:41626:35)
    at Function.cljs.analyzer.analyze_seq.cljs$core$IFn$_invoke$arity$4 ([stdin]:41676:45)
    at cljs$analyzer$analyze_seq ([stdin]:41643:40)
    at cljs.core.reduce.call.or__4069__auto__ ([stdin]:41912:48)
    at Function.cljs.analyzer.analyze.cljs$core$IFn$_invoke$arity$4 ([stdin]:41943:8)
```
I don't know enough about cljs bootstrapping to know how much functionality is related between the available REPLs.

**Comment by mfikes** [comment]
@kanaka ^ you may find this one interesting as well

**Comment by mfikes** [comment]
http://dev.clojure.org/jira/browse/CLJS-1321

**Comment by aengelberg** [comment]
Apparently has been fixed in ClojureScript master.

**Comment by mfikes** [comment]
Yes. I was attempting to confirm the fix, but I now get an error regarding `name.getNamespace()'

**Comment by mfikes** [comment]
Ahh... it is fixed (or at least has moved on to the next error regarding `set!`. My issue is I needed to blow away my resources directory.

**Comment by kanaka** [comment]
The "set!" error is: http://dev.clojure.org/jira/browse/CLJS-1325

**Comment by mfikes** [comment]
Now, we are down to this:

```
(defrecord R [])
```

```
WARNING: No such namespace: core, could not locate core.cljs, core.cljc, or Closure namespace ""
WARNING: Use of undeclared Var core/list
```

**Comment by asheldo** [comment]
So, is the remaining error this?:   SyntaxError: Unexpected token .

Unless I am missing something with the expression. This also happens when I'm just def'ing a var. Maybe it is related to analyzer.cljc(defn resolve-var [env sym])? The result prior to js/eval is:
```javascript
cljs-bootstrap.core=>  (with-out-str (ensure (c/emit (no-warn (ana/analyze
              (assoc (ana/empty-env) :context :expr)
              '(def v 1))))))
".v = 1" 
```
Same with `(def v# 1) and defrecord when I try in cljs-bootstrap.

**Comment by mfikes** [comment]
@asheldo With the latest master, I can't see, owing to #63

**Comment by aengelberg** [comment]
Can this be closed?

**Comment by mfikes** [comment]
Yep. 👍
