### ISSUE TITLE
Inaccurate error message

### ISSUE THREAD

**Issue by novemberkilo** [mfikes/replete#29]
Admittedly a syntax error but the error message appears to be incorrect?

      (seq (1 2))

      At least one digit must occur after a decimal point
      eval@[native code]
      file:///replete/core.js:95:59
      replete$core$read_eval_print@file:///replete/core.js:106:3

**Comment by karlmikko** [comment]
the error occurs when evaling `(1 2)` before it gets to the `seq`

**Comment by mfikes** [comment]
This misleading error message is because the following JavaScript is emitted for `(1 2)`: `1.call(null,2)`

If #46 is addressed, then this would emit `(1).call(null,(2))`, which produces an error that looks like

```
TypeError: undefined is not a function (evaluating '(1).call(null,(2))')
```

**Comment by mfikes** [comment]
Now `(seq (1 2))` causes:

`(1).call is not a function. (In '(1).call(null,(2))', '(1).call' is undefined`

Closing as good enough now.
