### ISSUE TITLE
scrolling can be jumpy

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#30]
If you have a sufficient amount of history showing and you try to scroll, it stutters. It can become smooth if you scroll up and down until you evaluate another form.

**Comment by mfikes** [comment]
See https://github.com/smileyborg/TableViewCellWithAutoLayoutiOS8/issues/17

**Comment by mfikes** [comment]
I've committed what should be a fix, but not working.

**Comment by kahunamoore** [comment]
From a trusted source: "19581195 appears to be fixed in iOS 9 :)  A possible workaround might be to cache the true row heights during scrolling and return them from -tableView: heightForRowAtIndexPath:, rather than always using UITableViewAutomaticDimension."

Hope this helps.

**Comment by mfikes** [comment]
@kahunamoore Sweet. Easy enough to try!

**Comment by mfikes** [comment]
@kahunamoore Calculating and cacheing is probably more work than I thought. But, I did confirm that it is indeed fixed in iOS 9. So, I think I'll just close this issue and not worry about working around in iOS 8.
