### ISSUE TITLE
associate request and response

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#42]
```
(loop [x 1000000000] 
  (if (pos? x) 
    (recur (dec x))))
```

takes a while, and other forms can be queued. It would be nice to hook responses to requests in history.

**Comment by mfikes** [comment]
Perhaps a cleaner alternative would be to allow only one execution be queued at a time (blocking the main thread when a second form is evaluated), thus guaranteeing serial nature, while still allowing the user to enter and edit the next form if a long-running form is being evaluated.

**Comment by karlmikko** [comment]
Could also build a queue internally and only execute one at a time. This would allow the main thread to still be active and allow users to scroll etc.

**Comment by mfikes** [comment]
Yeah. It is also looking like `cljs.js` has some async aspects to it, so we'll see what happens there.

**Comment by mfikes** [comment]
Hmm... looks like with Parinfer calling into JS engine, things simply lock up now.

Nobody has been really complaining about this one, so not worrying about associating requests and responses for now.
