### ISSUE TITLE
Error Message goes past screen width.

### ISSUE THREAD

**Issue by currentoor** [mfikes/replete#51]
When I try to eval something win an error in it, the error message goes past the screen width making it hard to read the whole thing. Not a huge deal but should be easy to fix.

![image_6245046848](https://cloud.githubusercontent.com/assets/2679997/8611711/42e893b4-267a-11e5-9628-64144065f233.jpg)

**Comment by mfikes** [comment]
Dup of #1 which is now in build (14)
