### ISSUE TITLE
Recursive function crashes the app.

### ISSUE THREAD

**Issue by currentoor** [mfikes/replete#52]
A mundanely recursive function makes the app crash if the call stack gets too large. In the clojure repl it gracefully throws a stack too deep error.

Simple example function
```clojurescript
(defn foo [] (foo))
```

**Comment by mfikes** [comment]
@currentoor Thanks! This works on an iPhone 6. Which device do you have? (I'm wondering if we are running out of memory and need to be more careful.) Can you try with the latest build (14) that was just released?

**Comment by mfikes** [comment]
![img_0824](https://cloud.githubusercontent.com/assets/1723464/13538102/9489d5ae-e216-11e5-845b-4209c19f66f9.jpg)

**Comment by mfikes** [comment]
Not reproducible.
