### ISSUE TITLE
for crashes

### ISSUE THREAD

**Issue by ulsa** [mfikes/replete#53]
`(for [x 1 y 2] y)` crashes with "Can't recur here"

**Comment by mfikes** [comment]
http://dev.clojure.org/jira/browse/CLJS-1334

**Comment by asheldo** [comment]
I attached to CLJS-1334 a clojurescript patch for the issue with the for macro.

**Comment by mfikes** [comment]
@asheldo I tested it with cljs-bootstrap and see it is resolved there. I couldn't confirm it being fixed with Replete (still getting the `recur` error).

**Comment by asheldo** [comment]
@mfikes I need to update Xcode etc in order to try this with Replete/simulator.

**Comment by asheldo** [comment]
I did better testing this time, still not with replete, just with cljs-bootstrap. Patch v2 is uploaded -- fix is to the when-first reference in the core.cljc for defmacro.

**Comment by mfikes** [comment]
@asheldo Your latest patch works for me.

**Comment by mfikes** [comment]
Fixed for `(for [x [1] y [2]] y)`
