### ISSUE TITLE
re-seq error

### ISSUE THREAD

**Issue by ghufransyed** [mfikes/replete#67]
Version 1.0(14) 

(re-seq #"jam" "I like jam in my jam ")

Invalid escape in identifier: '\' 
 eval@[native code]
file:///replete/core.js:206:111
replete$core$read_eval_print@file:///replete/core.js:225:3

(doc re-seq)
-------------------------
cljs.core/re-seq
([re s])
  Returns a lazy sequence of successive matches of re in s.

(re-seq #"bl" "bl" )
Invalid escape in identifier: '\' 
 eval@[native code]
file:///replete/core.js:206:111
replete$core$read_eval_print@file:///replete/core.js:225:3

**Comment by mfikes** [comment]
Thanks! The version in dev has been updated to use 1.7.28 and returns:

````
("jam" "jam")
```

```
("bl")
```

**Comment by mfikes** [comment]
Fixed.
