### ISSUE TITLE
recommend `prn` rather than `println` for the P part of REPL

### ISSUE THREAD

**Issue by scgilardi** [mfikes/replete#7]
Other Clojure REPLs use `prn` to print and that seems appropriate here as well.

In some cases (like strings), `prn` gives a clearer indication of the type of the output which is helpful.

**Comment by mfikes** [comment]
Right. I probably shouldn't be using `println` here: https://github.com/mfikes/replete/blob/1.0-beta.2/ClojureScript/replete/src/replete/core.cljs#L43
