### ISSUE TITLE
Provide means to edit files

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#71]
We can load files into Replete, but we can't currently edit files. Maybe it is possible to make a simple editor to at least let people muck around with source directly on the device.

See https://twitter.com/timbaldridge/status/648913822036660226

**Comment by kenny-evitt** [comment]
If you can load files then we could use another editor and open them in Replete to evaluate them. Tho it would be awesome to be able to edit like in [Lisping](http://slidetocode.com/lisping).

**Comment by mfikes** [comment]
@kenny-evitt You _can_ use Lisping. Here is a demo of it in action: https://youtu.be/a4macOje71c

**Comment by kenny-evitt** [comment]
@mfikes That's a great video :smile: 

I figured I could do what the video demonstrates. I meant that it would be great to be able to edit like in Lisping *within* Replete. But hey, it's pretty close as-is, so I'll take it!

**Comment by mfikes** [comment]
We can no longer load files into Replete (App Store rules), so closing this. It will probably just raise questions.
