### ISSUE TITLE
source mapping causes hang behavior

### ISSUE THREAD

**Issue by mfikes** [mfikes/replete#76]
Now with calls into ClojureScript while editing (for Parinfer) source mapping looks like a keyboard hang

Try `(ffirst 1)` and then type

**Comment by mfikes** [comment]
This occurs only for the first exception encountered

**Comment by maxthoursie** [comment]
I can reproduce. The hang eventually returns and it's working as normal again.

**Comment by mfikes** [comment]
Source mapping is turned off.
