### ISSUE TITLE
is there a way to 'use' a library?

### ISSUE THREAD

**Issue by pvinis** [mfikes/replete#95]

**Comment by mfikes** [comment]
It used to be possible to load arbitrary libs (http://blog.fikesfarm.com/posts/2015-08-11-loading-clojurescript-into-your-iphone.html) but Apple won't allow that style. Replete ships with a few libs bundled in.

**Comment by pvinis** [comment]
ah right. makes sense. thank you


-- 
Pavlos Vinieratos
